### ISSUE TITLE
How to format error message?

### ISSUE THREAD

**Issue by VuongVu** [relay-tools/react-relay-network-modern#105]
Like the article, when i got error message from server, it display: 
```
RRNLRequestError: Relay request for `signInMutation` failed by the following reasons:

1. AuthenticationError: Invalid password

```
How can i config to remove the first line of message, my error message got from server is: `AuthenticationError: Invalid password`

**Comment by PiTiLeZarD** [comment]
I'm checking that exact thing at the moment. Have you found anything useful regarding this? What I figured so far is that it happens here:
https://github.com/relay-tools/react-relay-network-modern/blob/master/src/createRequestError.js#L83

and it doesn't seem very customisable :/

**Comment by PiTiLeZarD** [comment]
Sorry for the double comment here, I did manage to find a way eventually, you can add that middleware all the way after the urlMiddleware:

```
const errorRethrow = (opts) => (next) => async (req) => {
    const res = await next(req);
    if (res.errors.length) {
        throw new RRNLRequestError(res.errors[0].message);
    }
    return res;
};
```

**Comment by VuongVu** [comment]
> Sorry for the double comment here, I did manage to find a way eventually, you can add that middleware all the way after the urlMiddleware:
> 
> ```
> const errorRethrow = (opts) => (next) => async (req) => {
>     const res = await next(req);
>     if (res.errors.length) {
>         throw new RRNLRequestError(res.errors[0].message);
>     }
>     return res;
> };
> ```

Thanks so much, it looks good to me. Thanks for taking your time to support me :smile:
