### ISSUE TITLE
New fetchQuery (relay v11) does not trigger middleware request on the server

### ISSUE THREAD

**Issue by aalises** [relay-tools/react-relay-network-modern#127]
Hello!

I have recently upgraded to [Relay v11](https://github.com/facebook/relay/releases/tag/v11.0.0), which includes some changes to `fetchQuery`.

I am using it to fetch some data on the client for SSR hydration. However, with the new version, it's not triggering any middleware when calling it (it did on v10), as if it didn't hit the network. Any idea what could go wrong?

```js
import {
  RelayNetworkLayer,
  urlMiddleware,
} from "react-relay-network-modern/node8";
...
export async function getSSRData(
  query: GraphQLTaggedNode,
  variables?: Variables
): Promise<Array<[string, QueryPayload]> | null> {
  const source = new RecordSource();
  const store = new Store(source);

 const environment = new Environment({
      store,
      network: new RelayNetworkLayer([
        urlMiddleware({
          url: () => process.env.GRAPHQL_URI ?? "http://localhost:4000",
        }),
        next => async req => { console.log(req); /* not called */ }
      ]),
    }),

  await fetchQuery(environment, query, variables ?? {});
  
  ...
}
```

Using the old `fetchQuery` works though (`fetchQuery_DEPRECATED`)

**Comment by AnotherHermit** [comment]
With `fetchQuery` now returning an Observable instead of a promise by default, I had to use `fetchQuery(...).toPromise()` to get everything to work as it did before.

**Comment by aalises** [comment]
Yes! that works for me as well! thanks @AnotherHermit
