### ISSUE TITLE
Add 'credentials' to RelayRequestBatch's fetchOpts if each request's fetchOpts has set credentials

### ISSUE THREAD

**Issue by jepezi** [relay-tools/react-relay-network-modern#15]
(I've created pull request here https://github.com/nodkz/react-relay-network-modern/pull/14 and let's discuss it here.)

My issue is that fetch doesn't send with credentials option when both url and batch middleware are used. Here is the code. 

```js
const network = new RelayNetworkLayer([
  cacheMiddleware({
    size: 100,
    ttl: 900000,
  }),
  urlMiddleware({
    credentials: 'include', // <-----------  credentials here is not set on fetch
    url: 'http://localhost:3000/graphql',
  }),
  batchMiddleware({
    batchUrl: 'http://localhost:3000/graphql/batch',
    batchTimeout: 10,
  }),
])
```

When I look at the code, it seems RelayRequestBatch ignores fetchOpts that is set from urlMiddleware ([code here](https://github.com/nodkz/react-relay-network-modern/blob/master/src/RelayRequestBatch.js#L14)). 

The code in PR just checks the credentials option and set it accordingly. Not sure if it's the best way to do it tho. What do you think?

**Comment by nodkz** [comment]
Good catch @jepezi 

Maybe we just add `credentials` option and other to `batchMiddleware` like id did in `urlMiddleware`? In such case will be more granular setup for `batchMiddleware` and `urlMiddleware` which can be different.

So your config will be in following form:
```js
const network = new RelayNetworkLayer([
  cacheMiddleware({
    size: 100,
    ttl: 900000,
  }),
  urlMiddleware({
    credentials: 'include',
    url: 'http://localhost:3000/graphql',
  }),
  batchMiddleware({
    credentials: 'include', // <-----------  credentials should be defined explicitly
    batchUrl: 'http://localhost:3000/graphql/batch',
    batchTimeout: 10,
  }),
])
```

**Comment by jepezi** [comment]
Yeah good idea. You can close my PR now. :)

**Comment by nodkz** [comment]
Will you make a new one? 😇

**Comment by jepezi** [comment]
Done. https://github.com/nodkz/react-relay-network-modern/pull/16

**Comment by joelvh** [comment]
@nodkz close this?
