### ISSUE TITLE
retryMiddleware does not retry on Network request failed error

### ISSUE THREAD

**Issue by ntelkedzhiev** [relay-tools/react-relay-network-modern#36]
What is the reasoning behind the check on 112 in `middlewares/retry.js`:

```javascript
if (e && e.res && o.retryOnStatusCode(e.res.status, o.req, e.res)) {
```

In a case where the request does not reach the server (network connection problem, etc.), this check fails and the error is rethrown instead of a making another retriable request. Have you considered handling such cases?

**Comment by nodkz** [comment]
Good catch!
Nope `network connection problem` did not considered. But it SHOULD.

Can you make PR?

**Comment by ntelkedzhiev** [comment]
Yes, I will in a bit. I will also add a callback to trigger on every request. It should bring a wide range of applications. We particularly need it to show a connection status bar once the initial request fails/timeouts. I might include our case as a sample usage in the docs.
