### ISSUE TITLE
Any ideas on adding Typescript support?

### ISSUE THREAD

**Issue by ivosabev** [relay-tools/react-relay-network-modern#49]

**Comment by xyy94813** [comment]
There are some tools to do this.

[@gimenete/type-writer](https://www.yarnpkg.com/en/package/@gimenete/type-writer)
[flow-to-dts](https://www.yarnpkg.com/en/package/flow-to-dts)

**Comment by nodkz** [comment]
This package updates very rare.
So you may add d.ts files directly to this package via Pull Request.

I don't have bandwidth to do it myself. So any help very appreciated 🙏

**Comment by cliedeman** [comment]
I have a [version](https://gist.github.com/cliedeman/ddbfafb46cec19dec55f04aaac433d79) I have been using locally that could probably do with some fine tuning.

Would need to export for the subfolders but other than some final sanity checks its probably quite close. I converted it directly from the flow types a few months ago

**Comment by nodkz** [comment]
Will be great. Please open Pull Request i'll review ts typings. 👍

**Comment by cliedeman** [comment]
#55 created

**Comment by nodkz** [comment]
Great, try to review it tomorrow!
I'm already sleeping 😴

**Comment by xyy94813** [comment]
@cliedeman I just modified the `abort` API, see [commit](https://github.com/relay-tools/react-relay-network-modern/commit/e80808216fd015360baf2d680dcfc6e5b1f54054)

**Comment by cliedeman** [comment]
@xyy94813 updated

**Comment by ivosabev** [comment]
Thanks, @cliedeman!

**Comment by xyy94813** [comment]
Is this a bug?

![image](https://user-images.githubusercontent.com/17971352/55703066-30b7c200-5a0b-11e9-9e56-f3d10fef856a.png)

I didn't see any definition of `operationKind`.

https://github.com/relay-tools/react-relay-network-modern/blob/011766b764b594270e04f5c2d8850449fe35913e/src/RelayRequest.js#L15

https://github.com/relay-tools/react-relay-network-modern/blob/011766b764b594270e04f5c2d8850449fe35913e/src/definition.js#L76-L84

Also, when I write middleware using Typescript, I don't need source code.
So, splitting the type declaration into another package is better, just like `@types/lodash`.

There is a repository that does something similar in github: [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by ivosabev** [comment]
Having to rely on types from DefinitelyTyped is a nuisance since it creates unnecessary dependency.
