### ISSUE TITLE
[BUG] Only refresh token once, if refresh token failed

### ISSUE THREAD

**Issue by xyy94813** [relay-tools/react-relay-network-modern#50]
There are some problem:
If refresh token failed, the auth middleware never retry to refresh token.

1. refresh token failed
2. target sign out
3. re sign in
4. access token timeout
5. then it will not try to refresh token.

Can I have any way to solve this problem?

https://github.com/relay-tools/react-relay-network-modern/blob/47806aa905702436307c00a192354540629ac5b6/src/middlewares/auth.js#L33-L71

the `tokenRefreshInProgress` never reset state if refresh token failed

**Comment by xyy94813** [comment]
it is better to change to:


```js
// before
tokenRefreshInProgress.then(newToken => { 
             const newReq = req.clone(); 
             newReq.fetchOpts.headers[header] = `${prefix}${newToken}`; 
             return next(newReq); // re-run query with new token 
           })
//after
tokenRefreshInProgress.then(newToken => { 
             const newReq = req.clone(); 
             newReq.fetchOpts.headers[header] = `${prefix}${newToken}`; 
             return next(newReq); // re-run query with new token 
           }).finally(() => {
             tokenRefreshInProgress = null; 
           })
```

**Comment by nodkz** [comment]
`Promise.finally` in Stage-4, so better to use `then/catch` and fix only the following code:

```diff
              tokenRefreshInProgress = Promise.resolve(tokenRefreshPromise(req, e.res)).then(
                newToken => {
                  tokenRefreshInProgress = null;
                  return newToken;
                }
+              ).catch(e => { tokenRefreshInProgress = null; throw e;});
```

Please open Pull Request. Thanks.
