### ISSUE TITLE
[Feature] RetryMiddleware aborted with custom error message in `beforeRetry`

### ISSUE THREAD

**Issue by xyy94813** [relay-tools/react-relay-network-modern#53]
I want to be able to customize the error message, when i use `beforeRetry`, so that I can distinguish between different terminations and make different behaviors.

It is easy to implement  like this: 
```js
abort = msg => {
    if (delayId) {
    clearTimeout(delayId);
    delayId = null;
    }
    reject(new RRNLRetryMiddlewareError(msg || 'Aborted in beforeRetry() callback'));
};
```

**Comment by nodkz** [comment]
You may copy the code of RetryMiddleware then implement a new logic and test it with your app.
And after that, if you like your solution and want to share with community – please open Pull Request with this awsome feature. 😉

Thanks!
