### ISSUE TITLE
batchMiddleware only one request at a time mode.

### ISSUE THREAD

**Issue by graingert** [relay-tools/react-relay-network-modern#7]
once queries have been queued due to the batch timeout. Create a new queue and wait for:

`Promise.all(oldBatch, sleep(batchTimeout))` before issuing the next batch.

This should also apply to retries etc. Eg if a request has failed due to a retry the next trail should include new batched requests.

**Comment by graingert** [comment]
This would be also neat if we could apply this for all tabs using localStorage or etc.

**Comment by graingert** [comment]
maybe even support n requests at a time?

**Comment by nodkz** [comment]
`localStorage` is a bad idea, cause it may bring problems for react-native users.

Limiting of the number of requests per batch is a good idea (unlimited by default). Fill free to make PR ;)

I don't know is it good to not send next batch while previous has not arrived. It may bring bad UX for some cases. But it can be implemented as separate middleware with controls number of active requests. So it can be used not only with batching ;) Can you write such MW?

PS. In my app, I completely disable batching and prefer to send 3-4 requests and render different parts of my app when the response arrived. In such case users got better UX, they see that page is loading/rendering and is it better than just display spinner.

**Comment by graingert** [comment]
This would be really helpful in https://github.com/nodkz/react-relay-network-modern/issues/8

**Comment by nodkz** [comment]
Fixed in v4.0.0 by @joelvh 👍
https://github.com/relay-tools/react-relay-network-modern/releases/tag/v4.0.0

Please reopen if problems occur.
