### ISSUE TITLE
batchMiddleware + server support EventSource streaming responses

### ISSUE THREAD

**Issue by graingert** [relay-tools/react-relay-network-modern#8]
where possible the server should be able to return an LD-JSON stream of resolved queries. The batch middleware should be able to resolve individual queries as their batched result arrives.

**Comment by nodkz** [comment]
In such case better to write your own custom middleware. Just copy code of batch MW and try to rewrite it for your own needs.

**Comment by nodkz** [comment]
Fixed in v4.0.0 by @joelvh 👍
https://github.com/relay-tools/react-relay-network-modern/releases/tag/v4.0.0

Please reopen if problems occur.
