### ISSUE TITLE
Add type definitions to return types on functions `createRequestError` and `formatGraphQLErrors`

### ISSUE THREAD

**Issue by deluksic** [relay-tools/react-relay-network-modern#96]
These functions (`createRequestError` and `formatGraphQLErrors`) don't have return type annotations. When using this library with typescript in strict mode, builds fail.

**Comment by deluksic** [comment]
Looking at the original flow types, I guess these should be actual types:
```typescript
export function createRequestError(request: RelayRequestAny, response?: RelayResponse): RRNLRequestError;
export function formatGraphQLErrors(request: RelayRequest, errors: GraphQLResponseErrors): string;
```

**Comment by nirvdrum** [comment]
Sorry for the headache. I introduced the original definitions. I run TypeScript in strict mode, so I'm not sure why I didn't see the same thing you did. But, thanks for fixing.

**Comment by deluksic** [comment]
No worries! Maybe different typescript version? I was running latest ts.
